### ISSUE TITLE
finished with non-zero exit value 2

### ISSUE THREAD

**Issue by renbingGitHub** [marcshilling/react-native-image-picker#236]
"react-native-image-picker": "^0.19.4" 

react-native run-android  FAILURE: Build failed with an exception.

Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\jdk1.8.0_91\bin\java.exe'' finished with non-zero exit value 2

**Comment by yfuks** [comment]
Make sure you updated your **RN** version correctly.
Are you sure that this issue is related with this module ?

**Comment by 277850318** [comment]
me too 

Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define La
ndroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexM
erger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerg
er.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerg
er.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.j
ava:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:1
89)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuff
ers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.jav
a:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)

Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'D:\Program Files\Java\jdk1.8.0_66\bin\java.exe''
 finished with non-zero exit value 2

**Comment by yfuks** [comment]
**Are you sure that this issue is related with this module ?**
I don't see any file from this module in your stack trace

**Comment by renbingGitHub** [comment]
The last version is still good, updated to 0.19.4 after the start on the wrong, if you get rid of all the normal react-native-image-picker module, RN is the latest film, I do not know what reason.

**Comment by marcshilling** [comment]
This is fixed in `0.19.5`. It was happening because I had checked in an `.iml` file

**Comment by pampang** [comment]
I am in the version of `0.19.5` but still got this error, my RN version is `0.25.1`.

**Comment by 277850318** [comment]
"dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.0",
    "react-native-image-picker": "^0.19.5"
  }

still show the error

Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'D:\Program Files\Java\jdk1.8.0_66\bin\java.exe''
 finished with non-zero exit value 2

**Comment by srdjan-kolosek** [comment]
Im having the same error when i try to add image-picker to basic react native example project and run react-native run-android.

"dependencies": {
    "react": "15.1.0",
    "react-native": "0.28.0",
    "react-native-image-picker": "^0.19.6"
  }

This is part of my build.gradle: 

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.imgpickertest"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-image-picker')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

**Comment by srdjan-kolosek** [comment]
Problem was that I was using old grade version. Updgraded it and it works

**Comment by 277850318** [comment]
what your grade version @srdjan-kolosek

**Comment by srdjan-kolosek** [comment]
In gardle.wrapper.properties distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip,
and in android/build.gradle classpath 'com.android.tools.build:gradle:2.1.0'
