### ISSUE TITLE
[Android] React Native 0.28 error

### ISSUE THREAD

**Issue by felipemendesbraga** [marcshilling/react-native-image-picker#257]
Hi,

I'm trying to upgrade my project to use release 0.28, but when I try to run on Android, show this:
```
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2
```

my gradle.build:
```
...
dependencies {
    compile project(':react-native-image-picker')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
...
```
I installed another packages like vector-icons and this error didn't happened, only when I added image-picker module.
Can someone help me with this problem?

**Comment by Andreyco** [comment]
Experience this issue as well. Can confirm that without `react-native-image-picker` linked project builds. Trying to find solution.

**Comment by Andreyco** [comment]
please, refer to #241, which contains solution for this issue.

**Comment by alexei-stapinski-intelex** [comment]
I'm hitting this issue as well, even on a simple Awesome project like #241 refers to with RN 0.29. On a fresh npm install of 0.20.1, the android/build folder is populated with build items. If I remove the android/build folder and run react-native run-android, it works. I'm fairly new to Android/RN dev, but is it normal to have build files in a package like this?

**Comment by yfuks** [comment]
Nop :)

**Comment by yfuks** [comment]
After the first build it's normal, but not after a simple ```npm install react-native-image-picker```

**Comment by marcshilling** [comment]
How can we fix this? Why are build items pre-populated on a fresh `npm install`?

**Comment by yfuks** [comment]
Just need to be sure that we remove ```android/build``` before publishing a new version 
Basically we have to remove all builds folders (there are multiples ```build``` folder that are created) and ```nodes_modules```

**Comment by Andreyco** [comment]
I would say this is "normal Android dev flow" :D

**Comment by marcshilling** [comment]
But `android/build` is not checked in...so how is this happening?

**Comment by alexei-stapinski-intelex** [comment]
So the Github repo naturally doesn't have it. When I look at the (evidently) downloaded NPM package with this URL (https://registry.npmjs.org/react-native-image-picker/-/react-native-image-picker-0.20.1.tgz), it has the build folder. It's also around 60 MB.

**Comment by marcshilling** [comment]
Thanks @alexei-stapinski-intelex. I just published `v0.20.2` and confirmed the package downloaded from `npm` does not include the build folder. This shouldn't be an issue anymore.

**Comment by alexei-stapinski-intelex** [comment]
Thanks for looking into it! It's confirmed OK over here now.

**Comment by cauchycai** [comment]
Still seeing this issue in v0.21.1 , while I am using react-native built from source. After I remove react-native-image-picker/android/build folder, it then works.

**Comment by marcshilling** [comment]
UGH, this is insanely annoying. Every time I publish without remembering to delete the `build/` folder first, this will happen. npm is supposed to be ignoring files that match the `.gitignore`, but it goes ahead and publishes the build folder anyway. I'll try adding an `.npmignore` that duplicates the `.gitignore`...

**Comment by marcshilling** [comment]
Nope, even with an `.npmignore`, it still publishes the build folder....INFURIATING!!!!
We're just gonna have to live with this one...there's no way I'll remember to delete the folder every time I do a new version 😞

**Comment by marcshilling** [comment]
Ok, this should never happen again in future builds

https://github.com/marcshilling/react-native-image-picker/releases/tag/v0.21.4
