### ISSUE TITLE
[Android] - Image is being saved in the Pictures folder even though the storageOptions is not specified

### ISSUE THREAD

**Issue by sandrarivera** [marcshilling/react-native-image-picker#273]
The documentation says:

**storageOptions:**
If this key is provided, the image will get saved in the Documents directory on iOS, and the Pictures directory on Android (rather than a temporary directory)

I'm not providing the storageOption property and the pictures are being saved in the 'Pictures' folders. ex:

```
var options = {
  title: 'Select Avatar',
  customButtons: {
    'Choose Photo from Facebook': 'fb',
  },
};
```

Shouldn't the image be saved in a temp folder as per document? or am I missing something?

**Comment by yfuks** [comment]
With camera or gallery ?

**Comment by sandrarivera** [comment]
both

**Comment by sandrarivera** [comment]
it happens with both

**Comment by marcshilling** [comment]
Can you try out v0.22 on npm and see if this is still happening?

**Comment by iOSQiao** [comment]
hello, i use image picker on ios, my ViewController frame is CGRectMake(0, 20, UIScreenWidth, UIScreenHeight - 20). when I present the image picker, and selected the photo or cancel, dismiss image picker, my ViewController frame is  CGRectMake(0, 20, UIScreenWidth, UIScreenHeight - 20), that is not terrible. what happend it? Can you help me? Thank you.

**Comment by marcshilling** [comment]
This should be fixed in `v0.22.2`

**Comment by MaximusBaton** [comment]
Same thing still happening with the latest version (0.28.1) on Android 5.1.1
