### ISSUE TITLE
[iOS] [Generic] Creating an image format with an unknown type is an error

### ISSUE THREAD

**Issue by Riokai** [marcshilling/react-native-image-picker#380]
```sh
react-native-cli: 1.0.0
react-native: 0.36.0
xcode: 8.0
iOS: 10
```

**Comment by ChrisPikul510** [comment]
+1
Same here, not working on iOs. Tried with`allowsEditing` and without.

Configuration:

```
{
   title: 'Choose Profile Picture',
   mediaType: 'photo',
   maxWidth: 512,
   maxHeight: 512,
   allowsEditing: true,
   storageOptions: {
      skipBackup: true,
      cameraRoll: false,
      waitUntilSaved: true
   }
}
```

react-native-image-picker: 0.22.13
react-native: 0.35
xcode: 8.0
iOs: 10 (deployment target is 8.2)

**Comment by marcshilling** [comment]
The issue is the combination of `cameraRoll: false` and `waitUntilSaved: true`. Fixing it now...

**Comment by marcshilling** [comment]
Should be fixed in `v0.22.14` on npm!

**Comment by JeffersonFilho** [comment]
I'm still facing this issue using 
react-native-image-picker: 0.23.0
react-native-cli: 1.0.0
react-native: 0.37.0
iOS: 10
xcode: Version 8.1 (8B62)

`<Error>: [Generic] Creating an image format with an unknown type is an error`

**Comment by hhashmi** [comment]
I'm still facing this issue using
react-native-image-picker: 0.24.1
react-native-cli: 1.0.0
react-native: 0.34.0
iOS: 10.12
xcode: Version 8

<Error>: [Generic] Creating an image format with an unknown type is an error

**Comment by pap5508** [comment]
@marcshilling getting this error While select photo from Simulator gallery 

`Feb 24 10:37:56 --- last message repeated 1 time ---
[Generic] Creating an image format with an unknown type is an error
*** ASL MESSAGE SIZE (25813666 bytes) EXCEEDED MAXIMIMUM SIZE (8192000 bytes) ***`


Package.json

"nativescript-imagepicker": "^2.5.1",

**Comment by marcshilling** [comment]
This is just a warning correct? Everything still works?

**Comment by Jeff-KaayLabs** [comment]
Even from Swift I have this warning

**Comment by antoinerousseau** [comment]
could be a false warning
https://stackoverflow.com/a/41349385/1052033
